services:
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "8081:8081"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
    depends_on:
      - inventory-service
